---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes 
summary: 'L"aggiunta di provider di bucket di archivi di oggetti è essenziale se si desidera eseguire il backup delle applicazioni e dello storage persistente di se si desidera clonare le applicazioni tra cluster.' 
---
= Gestire i bucket
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Un provider di bucket dell'archivio di oggetti è essenziale se si desidera eseguire il backup delle applicazioni e dello storage persistente o se si desidera clonare le applicazioni tra cluster. Utilizzando Astra Control Center, Aggiungi un provider di archivi di oggetti come destinazione di backup off-cluster per le tue applicazioni.

Non è necessario un bucket se si clonano la configurazione dell'applicazione e lo storage persistente sullo stesso cluster.

Utilizzare uno dei seguenti provider di bucket:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Generico S3



NOTE: Sebbene Astra Control Center supporti Amazon S3 come provider di bucket S3 generico, Astra Control Center potrebbe non supportare tutti i vendor di archivi di oggetti che sostengono il supporto S3 di Amazon.

Non è possibile eliminare un bucket, tuttavia è possibile modificarlo.

Un bucket può trovarsi in uno dei seguenti stati:

* In sospeso: Il bucket è pianificato per il rilevamento.
* Disponibile: La benna è disponibile per l'uso.
* Rimosso: Il bucket non è attualmente accessibile.


Per istruzioni su come gestire i bucket utilizzando l'API Astra Control, vedere link:https://docs.netapp.com/us-en/astra-automation/["Astra Automation e informazioni API"^].

È possibile eseguire queste attività relative alla gestione dei bucket:

* link:../get-started/setup_overview.html#add-a-bucket["Aggiungi un bucket"]
* <<Modificare un bucket>>



NOTE: I bucket S3 in Astra Control Center non riportano la capacità disponibile. Prima di eseguire il backup o la clonazione delle applicazioni gestite da Astra Control Center, controllare le informazioni del bucket nel sistema di gestione ONTAP o StorageGRID.



== Rimuovere le credenziali

Rimuovere le credenziali S3 da un account in qualsiasi momento utilizzando l'API Astra Control.

Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/astra-automation/index.html["Utilizzare l'API di controllo Astra"^].


TIP: Il primo set di credenziali aggiunto ad Astra Control è sempre in uso perché Astra Control utilizza le credenziali per autenticare il bucket di backup. Si consiglia di non rimuovere queste credenziali.



== Modificare un bucket

È possibile modificare le informazioni delle credenziali di accesso per un bucket e modificare se un bucket selezionato è il bucket predefinito.


NOTE: Quando si aggiunge un bucket, selezionare il bucket provider corretto e fornire le credenziali corrette per tale provider. Ad esempio, l'interfaccia utente accetta come tipo NetApp ONTAP S3 e accetta le credenziali StorageGRID; tuttavia, questo causerà l'errore di tutti i backup e ripristini futuri dell'applicazione che utilizzano questo bucket. Vedere link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["Note di rilascio"].

.Fasi
. Dalla barra di navigazione a sinistra, selezionare *Bucket*.
. Dal menu Actions (azioni), selezionare *Edit* (Modifica).
. Modificare qualsiasi informazione diversa dal tipo di bucket.
+

TIP: Impossibile modificare il tipo di bucket.

. Selezionare *Aggiorna*.




== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/astra-automation/index.html["Utilizzare l'API di controllo Astra"^]

