---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Descrive come rimuovere Astra Control Center e Astra Control Center Operator. 
---
= Disinstallare Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Potrebbe essere necessario rimuovere i componenti di Astra Control Center se si esegue l'aggiornamento da una versione di prova a una versione completa del prodotto. Per rimuovere Astra Control Center e Astra Control Center Operator, eseguire i comandi descritti in questa procedura in sequenza.

.Di cosa hai bisogno
* Utilizzare l'interfaccia utente di Astra Control Center per annullare la gestione di tutto link:../use/unmanage.html#stop-managing-compute["cluster"].


.Fasi
. Eliminare Astra Control Center. Il seguente comando di esempio si basa su un'installazione predefinita. Modificare il comando se sono state create configurazioni personalizzate.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Risultato:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utilizzare il seguente comando per eliminare `netapp-acc` spazio dei nomi:
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Risultato:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utilizzare il seguente comando per eliminare i componenti del sistema dell'operatore di Astra Control Center:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Risultato:

+
[listing]
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----




== Trova ulteriori informazioni

* link:../release-notes/known-issues.html["Problemi noti per la disinstallazione"]

