---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, cluster storage, cluster overview 
summary: Dopo aver aggiunto i cluster ad Astra Control Center, è possibile visualizzare i dettagli del cluster, ad esempio la sua posizione, i nodi di lavoro, i volumi persistenti e le classi di storage. 
---
= Visualizza lo stato di salute e i dettagli dei cluster
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Dopo aver aggiunto i cluster da gestire da Astra Control Center, è possibile visualizzare i dettagli del cluster, ad esempio la sua posizione, i nodi di lavoro, i volumi persistenti e le classi di storage.

.Fasi
. Nell'interfaccia utente di Astra Control Center, selezionare *Clusters*.
. Nella pagina *Clusters*, selezionare il cluster di cui si desidera visualizzare i dettagli.
. Visualizzare le informazioni nelle schede *Overview*, *Storage* e *Activity* per trovare le informazioni desiderate.
+
** *Panoramica*: Dettagli sui nodi di lavoro, incluso il loro stato.
** *Storage*: I volumi persistenti associati al calcolo, inclusi la classe e lo stato dello storage.
** *Attività*: Mostra le attività correlate al cluster.





NOTE: È inoltre possibile visualizzare le informazioni sul cluster partendo da Astra Control Center *Dashboard*. Nella scheda *Clusters* sotto *Riepilogo risorse*, è possibile selezionare i cluster gestiti, che consentono di accedere alla pagina *Clusters*. Una volta visualizzata la pagina *Clusters*, seguire la procedura descritta in precedenza.
